### ISSUE TITLE
Guicursor isn't set in new version of neovim

### ISSUE THREAD

**Issue by guillermorodriguez-wk** [pineapplegiant/dotfiles#1]
`set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
 \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
 \,sm:block-blinkwait175-blinkoff150-blinkon175
`

**Comment by pineapplegiant** [comment]
Great Job Guillermo I'll fix that rn homie!
